package gr.athenainnovation.imis.fusion.fetcher.gui;

import gr.athenainnovation.imis.fusion.fetcher.gui.listeners.DatasetListener;
import gr.athenainnovation.imis.fusion.fetcher.gui.listeners.MessageListener;
import gr.athenainnovation.imis.fusion.fetcher.gui.workers.DBConnectionParameters;
import gr.athenainnovation.imis.fusion.fetcher.gui.workers.Dataset;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 * Dataset panel.
 * @author Thomas Maroulis
 */
public class DatasetPanel extends javax.swing.JPanel {
    private List<DatasetListener> datasetListeners = new ArrayList<>();
    private MessageListener messageListener;
    
    /**
     * Creates new form DatasetPanel.
     */
    public DatasetPanel(MessageListener messageListener) {
        this.messageListener = messageListener;
        initComponents();
    }
    
    /**
     * Register dataset listener.
     * @param datasetListener dataset listener
     */
    public void registerDatasetListener(final DatasetListener datasetListener) {
        datasetListeners.add(datasetListener);
    }
    
    private void setSourceDataset(final Dataset sourceDataset) {
        for(DatasetListener listener : datasetListeners) {
            listener.setSourceDataset(sourceDataset);
        }
    }
    
    private void setTargetDataset(final Dataset targetDataset) {
        for(DatasetListener listener : datasetListeners) {
            listener.setTargetDataset(targetDataset);
        }
    }
    
    private void setDatasetsReady(final boolean datasetsReady) {
        for(DatasetListener listener : datasetListeners) {
            listener.setDatasetsReady(datasetsReady);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceDatasetPanel = new javax.swing.JPanel();
        sourceEndpointLabel = new javax.swing.JLabel();
        sourceGraphLabel = new javax.swing.JLabel();
        sourceEndpointField = new javax.swing.JTextField();
        sourceGraphField = new javax.swing.JTextField();
        sourceRemoteCheckbox = new javax.swing.JCheckBox();
        sourceDatasetStatusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sourceDatasetUnmodLocalGraphField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sourceDatasetModLocalGraphField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sourceDatasetRootNodeNS = new javax.swing.JTextField();
        targetDatasetPanel = new javax.swing.JPanel();
        targetEndpointLabel = new javax.swing.JLabel();
        targetEndpointField = new javax.swing.JTextField();
        targetGraphLabel = new javax.swing.JLabel();
        targetGraphField = new javax.swing.JTextField();
        targetRemoteCheckbox = new javax.swing.JCheckBox();
        targetDatasetStatusLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        targetDatasetUnmodLocalGraphField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        targetDatasetModLocalGraphField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        targetDatasetRootNodeNS = new javax.swing.JTextField();
        datasetPanelOkButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dbURLField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dbUsernameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dbPasswordField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        linkFileOrderToggle = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        linkFileField = new javax.swing.JTextField();
        linkFileChooserButton = new javax.swing.JButton();

        sourceDatasetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Source Dataset"));

        sourceEndpointLabel.setText("Endpoint:");

        sourceGraphLabel.setText("Graph:");

        sourceRemoteCheckbox.setText("Remote");
        sourceRemoteCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sourceRemoteCheckboxItemStateChanged(evt);
            }
        });
        sourceRemoteCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceRemoteCheckboxActionPerformed(evt);
            }
        });

        sourceDatasetStatusLabel.setText("Source dataset not set...");

        jLabel2.setText("Local graph (unmodified):");

        sourceDatasetUnmodLocalGraphField.setEditable(false);
        sourceDatasetUnmodLocalGraphField.setEnabled(false);

        jLabel1.setText("Local graph (transformed):");

        sourceDatasetModLocalGraphField.setEditable(false);
        sourceDatasetModLocalGraphField.setEnabled(false);

        jLabel9.setText("Root node namespace (regex):");

        javax.swing.GroupLayout sourceDatasetPanelLayout = new javax.swing.GroupLayout(sourceDatasetPanel);
        sourceDatasetPanel.setLayout(sourceDatasetPanelLayout);
        sourceDatasetPanelLayout.setHorizontalGroup(
            sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                        .addComponent(sourceRemoteCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sourceDatasetStatusLabel))
                    .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                        .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sourceEndpointLabel)
                                    .addComponent(sourceGraphLabel))
                                .addGap(18, 18, 18)
                                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sourceEndpointField)
                                    .addComponent(sourceGraphField)))
                            .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sourceDatasetUnmodLocalGraphField, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                    .addComponent(sourceDatasetModLocalGraphField)
                                    .addComponent(sourceDatasetRootNodeNS))))
                        .addContainerGap())))
        );
        sourceDatasetPanelLayout.setVerticalGroup(
            sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceEndpointLabel)
                    .addComponent(sourceEndpointField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceGraphLabel)
                    .addComponent(sourceGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceRemoteCheckbox)
                    .addComponent(sourceDatasetStatusLabel))
                .addGap(18, 18, 18)
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sourceDatasetRootNodeNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceDatasetUnmodLocalGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sourceDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sourceDatasetModLocalGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        targetDatasetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Target Dataset"));

        targetEndpointLabel.setText("Endpoint:");

        targetGraphLabel.setText("Graph:");

        targetRemoteCheckbox.setText("Remote");
        targetRemoteCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                targetRemoteCheckboxItemStateChanged(evt);
            }
        });
        targetRemoteCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetRemoteCheckboxActionPerformed(evt);
            }
        });

        targetDatasetStatusLabel.setText("Target dataset not set...");

        jLabel4.setText("Local graph (unmodified):");

        targetDatasetUnmodLocalGraphField.setEditable(false);
        targetDatasetUnmodLocalGraphField.setEnabled(false);

        jLabel3.setText("Local graph (transformed):");

        targetDatasetModLocalGraphField.setEditable(false);
        targetDatasetModLocalGraphField.setEnabled(false);

        jLabel10.setText("Root node namespace (regex):");

        javax.swing.GroupLayout targetDatasetPanelLayout = new javax.swing.GroupLayout(targetDatasetPanel);
        targetDatasetPanel.setLayout(targetDatasetPanelLayout);
        targetDatasetPanelLayout.setHorizontalGroup(
            targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                        .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetEndpointLabel)
                            .addComponent(targetGraphLabel))
                        .addGap(18, 18, 18)
                        .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetEndpointField)
                            .addComponent(targetGraphField)))
                    .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                        .addComponent(targetRemoteCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(targetDatasetStatusLabel))
                    .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                        .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetDatasetUnmodLocalGraphField)
                            .addComponent(targetDatasetModLocalGraphField)))
                    .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(targetDatasetRootNodeNS)))
                .addContainerGap())
        );
        targetDatasetPanelLayout.setVerticalGroup(
            targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetEndpointLabel)
                    .addComponent(targetEndpointField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetGraphLabel)
                    .addComponent(targetGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetRemoteCheckbox)
                    .addComponent(targetDatasetStatusLabel))
                .addGap(18, 18, 18)
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(targetDatasetRootNodeNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDatasetUnmodLocalGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(targetDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDatasetModLocalGraphField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datasetPanelOkButton.setText("Set");
        datasetPanelOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasetPanelOkButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Virtuoso connection"));

        jLabel6.setText("URL:");

        dbURLField.setText("localhost:1111");

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbPasswordField)
                    .addComponent(dbURLField)
                    .addComponent(dbUsernameField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dbURLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dbUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dbPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Link file"));

        linkFileOrderToggle.setText("Links: Source -> Target");
        linkFileOrderToggle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                linkFileOrderToggleItemStateChanged(evt);
            }
        });

        jLabel5.setText("Link file:");

        linkFileChooserButton.setText("...");
        linkFileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkFileChooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkFileOrderToggle)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(linkFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(linkFileChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(linkFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkFileChooserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkFileOrderToggle)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourceDatasetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(targetDatasetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datasetPanelOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(sourceDatasetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(targetDatasetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datasetPanelOkButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void datasetPanelOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasetPanelOkButtonActionPerformed
        try {
            DBConnectionParameters dbConnectionParameters = new DBConnectionParameters(dbURLField.getText(), dbUsernameField.getText(), dbPasswordField.getText());

            Dataset sourceDataset;
            if(!sourceRemoteCheckbox.isSelected()) {
                sourceDataset = new Dataset(sourceEndpointField.getText(), sourceGraphField.getText(), sourceRemoteCheckbox.isSelected(), sourceDatasetRootNodeNS.getText(), dbConnectionParameters);
            }
            else {
                sourceDataset = new Dataset(sourceEndpointField.getText(), sourceGraphField.getText(), sourceRemoteCheckbox.isSelected(), sourceDatasetRootNodeNS.getText(),
                        sourceDatasetUnmodLocalGraphField.getText(), sourceDatasetModLocalGraphField.getText(), dbConnectionParameters);
            }

            sourceDataset.setLinks(linkFileField.getText(), !linkFileOrderToggle.isSelected());

            setSourceDataset(sourceDataset);
            sourceDatasetStatusLabel.setText("Source dataset set!");
            
            Dataset targetDataset;
            if(!targetRemoteCheckbox.isSelected()) {
                targetDataset = new Dataset(targetEndpointField.getText(), targetGraphField.getText(), targetRemoteCheckbox.isSelected(), targetDatasetRootNodeNS.getText(), dbConnectionParameters);
            }
            else {
                targetDataset = new Dataset(targetEndpointField.getText(), targetGraphField.getText(), targetRemoteCheckbox.isSelected(), targetDatasetRootNodeNS.getText(),
                        targetDatasetUnmodLocalGraphField.getText(), targetDatasetModLocalGraphField.getText(), dbConnectionParameters);
            }

            targetDataset.setLinks(linkFileField.getText(), linkFileOrderToggle.isSelected());

            setTargetDataset(targetDataset);
            targetDatasetStatusLabel.setText("Target dataset set!");

            setDatasetsReady(true);
            setFieldEnabled(false);
        }
        catch (IllegalArgumentException | IllegalStateException ex) {
            messageListener.printMessageDialogue("Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_datasetPanelOkButtonActionPerformed

    private void setFieldEnabled(boolean status) {
        sourceEndpointField.setEditable(status);
        sourceGraphField.setEditable(status);
        sourceRemoteCheckbox.setEnabled(status);
        sourceDatasetRootNodeNS.setEditable(status);
        sourceDatasetUnmodLocalGraphField.setEditable(status);
        sourceDatasetModLocalGraphField.setEditable(status);
        
        targetEndpointField.setEditable(status);
        targetGraphField.setEditable(status);
        targetRemoteCheckbox.setEnabled(status);
        targetDatasetRootNodeNS.setEditable(status);
        targetDatasetUnmodLocalGraphField.setEditable(status);
        sourceDatasetModLocalGraphField.setEditable(status);
        
        linkFileField.setEditable(status);
        linkFileOrderToggle.setEnabled(status);
        linkFileChooserButton.setEnabled(status);
        
        dbURLField.setEditable(status);
        dbUsernameField.setEditable(status);
        dbPasswordField.setEditable(status);
        
        if(status) {
            sourceDatasetStatusLabel.setText("Source dataset not set...");
            targetDatasetStatusLabel.setText("Target dataset not set...");
        }
    }
    
    private void sourceRemoteCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sourceRemoteCheckboxItemStateChanged
        JCheckBox checkbox = (JCheckBox) evt.getSource();
        sourceDatasetUnmodLocalGraphField.setEditable(checkbox.isSelected());
        sourceDatasetModLocalGraphField.setEditable(checkbox.isSelected());
    }//GEN-LAST:event_sourceRemoteCheckboxItemStateChanged

    private void targetRemoteCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_targetRemoteCheckboxItemStateChanged
        JCheckBox checkBox = (JCheckBox) evt.getSource();
        targetDatasetUnmodLocalGraphField.setEditable(checkBox.isSelected());
        targetDatasetModLocalGraphField.setEditable(checkBox.isSelected());
    }//GEN-LAST:event_targetRemoteCheckboxItemStateChanged

    private void linkFileOrderToggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_linkFileOrderToggleItemStateChanged
        JToggleButton toggle = (JToggleButton) evt.getSource();
        if(!toggle.isSelected()) toggle.setText("Links: Source -> Target");
        else toggle.setText("Links: Target -> Source");
    }//GEN-LAST:event_linkFileOrderToggleItemStateChanged

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setDatasetsReady(false);
        setFieldEnabled(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void linkFileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkFileChooserButtonActionPerformed
        File file = new File(linkFileField.getText());
        final JFileChooser fileChooser = new JFileChooser(file);
        
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            linkFileField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_linkFileChooserButtonActionPerformed

    private void sourceRemoteCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceRemoteCheckboxActionPerformed
        JCheckBox checkbox = (JCheckBox) evt.getSource();
        sourceDatasetUnmodLocalGraphField.setEnabled(checkbox.isSelected());
        sourceDatasetModLocalGraphField.setEnabled(checkbox.isSelected());
    }//GEN-LAST:event_sourceRemoteCheckboxActionPerformed

    private void targetRemoteCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetRemoteCheckboxActionPerformed
        JCheckBox checkbox = (JCheckBox) evt.getSource();
        targetDatasetUnmodLocalGraphField.setEnabled(checkbox.isSelected());
        targetDatasetModLocalGraphField.setEnabled(checkbox.isSelected());
    }//GEN-LAST:event_targetRemoteCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datasetPanelOkButton;
    private javax.swing.JTextField dbPasswordField;
    private javax.swing.JTextField dbURLField;
    private javax.swing.JTextField dbUsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton linkFileChooserButton;
    private javax.swing.JTextField linkFileField;
    private javax.swing.JToggleButton linkFileOrderToggle;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sourceDatasetModLocalGraphField;
    private javax.swing.JPanel sourceDatasetPanel;
    private javax.swing.JTextField sourceDatasetRootNodeNS;
    private javax.swing.JLabel sourceDatasetStatusLabel;
    private javax.swing.JTextField sourceDatasetUnmodLocalGraphField;
    private javax.swing.JTextField sourceEndpointField;
    private javax.swing.JLabel sourceEndpointLabel;
    private javax.swing.JTextField sourceGraphField;
    private javax.swing.JLabel sourceGraphLabel;
    private javax.swing.JCheckBox sourceRemoteCheckbox;
    private javax.swing.JTextField targetDatasetModLocalGraphField;
    private javax.swing.JPanel targetDatasetPanel;
    private javax.swing.JTextField targetDatasetRootNodeNS;
    private javax.swing.JLabel targetDatasetStatusLabel;
    private javax.swing.JTextField targetDatasetUnmodLocalGraphField;
    private javax.swing.JTextField targetEndpointField;
    private javax.swing.JLabel targetEndpointLabel;
    private javax.swing.JTextField targetGraphField;
    private javax.swing.JLabel targetGraphLabel;
    private javax.swing.JCheckBox targetRemoteCheckbox;
    // End of variables declaration//GEN-END:variables
}
